# Generated by Django 4.0.3 on 2022-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('headzero', models.CharField(max_length=500)),
                ('cheadzero', models.CharField(max_length=500)),
                ('headone', models.CharField(max_length=500)),
                ('cheadone', models.CharField(max_length=500)),
                ('headtwo', models.CharField(max_length=500)),
                ('cheadtwo', models.CharField(max_length=500)),
                ('publish_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
