# Generated by Django 4.0.3 on 2022-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('dsc', models.CharField(max_length=300)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
